export const BARCODEYCOORDINATEADJUSTMENT = -50;

export const ADDITIONALPAGEHEIGHT = 5;
export const RANDOMNUMBERMULTIPLIER = 1000000000;

export const ALLOWEDBARCODEPOSITIONS = ["LEFT", "RIGHT", "MIDDLE"];

export const EXPORT_TYPES = ["PDF", "TIFF"];

export const BARCODE_GENERATION_RETRY = 5;

export const BARCODE_MIN_NUMBER = 1;
export const BARCODE_MAX_NUMBER = 9999999999;
export const BARCODE_LENGTH = 12;
export const BARCODE_PREFIX = "01";
