export const BARCODEYCOORDINATEADJUSTMENT = -45;

export const ADDITIONALPAGEHEIGHT = 5;
export const RANDOMNUMBERMULTIPLIER = 10000000000;

export const ALLOWEDBARCODEPOSITIONS = ["LEFT", "RIGHT", "MIDDLE"];
